import S1 from "./assests/img/S1.png";
import S2 from "./assests/img/S2.png";
import S3 from "./assests/img/S3.png";
import S4 from "./assests/img/S4.png";

export const products = [
  {
    id: 1,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    price: 125,
    tag: "New",
    size: [38, 39, 40, 41, 42], // Available sizes
    color: ["blue", "white"], // Available colors
    type: "Casual shoes", // Product type
    gender: "Men", // Suitable for Men
  },
  {
    id: 2,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    price: 125,
    tag: "Sale",
    size: [40, 41, 42, 43],
    color: ["green", "black"],
    type: "Runners",
    gender: "Men",
  },
  {
    id: 3,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    price: 125,
    tag: "New",
    size: [42, 43, 44],
    color: ["blue", "yellow"],
    type: "Sneaker",
    gender: "Men",
  },
  {
    id: 4,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    price: 125,
    tag: "New",
    size: [40, 41, 42],
    color: ["black", "white"],
    type: "Casual shoes",
    gender: "Women",
  },
  {
    id: 5,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    price: 125,
    tag: "Sale",
    size: [39, 40, 41, 42],
    color: ["green", "white"],
    type: "Hiking",
    gender: "Women",
  },
  {
    id: 6,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    price: 125,
    tag: "New",
    size: [41, 42, 43],
    color: ["blue", "green"],
    type: "Sneaker",
    gender: "Men",
  },
  {
    id: 7,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    price: 125,
    tag: "New",
    size: [38, 39, 40],
    color: ["blue", "black"],
    type: "Casual shoes",
    gender: "Women",
  },
  {
    id: 8,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    price: 125,
    tag: "Sale",
    size: [43, 44, 45],
    color: ["green", "orange"],
    type: "Golf",
    gender: "Men",
  },
  {
    id: 9,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    price: 125,
    tag: "New",
    size: [39, 40, 42],
    color: ["yellow", "blue"],
    type: "Basketball",
    gender: "Women",
  },
  {
    id: 10,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    price: 125,
    tag: "New",
    size: [38, 39, 40],
    color: ["white", "gray"],
    type: "Casual shoes",
    gender: "Women",
  },
  {
    id: 11,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    price: 125,
    tag: "Sale",
    size: [42, 43, 44],
    color: ["green", "black"],
    type: "Sneaker",
    gender: "Men",
  },
  {
    id: 12,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    price: 125,
    tag: "New",
    size: [39, 40, 41],
    color: ["blue", "green"],
    type: "Hiking",
    gender: "Women",
  },
  {
    id: 13,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    price: 125,
    tag: "New",
    size: [38, 39, 40],
    color: ["white", "red"],
    type: "Casual shoes",
    gender: "Women",
  },
  {
    id: 14,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    price: 125,
    tag: "Sale",
    size: [40, 41, 42],
    color: ["green", "yellow"],
    type: "Casual shoes",
    gender: "Men",
  },
  {
    id: 15,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    price: 125,
    tag: "New",
    size: [42, 43, 44],
    color: ["blue", "black"],
    type: "Runners",
    gender: "Men",
  },
  // Add more products as needed
];
