import S1 from "./assests/img/S1.png";
import S2 from "./assests/img/S2.png";
import S3 from "./assests/img/S3.png";
import S4 from "./assests/img/S4.png";
import S11 from "./assests/img/S11.png";
import S12 from "./assests/img/S12.png";
import S13 from "./assests/img/S13.png";
import S14 from "./assests/img/S14.png";

export const products = [
  {
    id: 1,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [38, 39, 40, 41, 42, 44, 45, 46, 47], 
    color: ["blue", "white"], 
    type: "Casual shoes", 
    gender: "Men",
    soldOutSizes: [40],
    description: "Shadow Navy / Army Green",
  },
  {
    id: 2,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "Sale",
    size: [40, 41, 42, 43], 
    color: ["green", "black"], 
    type: "Runners",
    gender: "Men",
    soldOutSizes: [41],
    description: "Deep Green / Black",
  },
  {
    id: 3,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [42, 43, 44], 
    color: ["blue", "yellow"], 
    type: "Sneaker",
    gender: "Men",
    soldOutSizes: [42],
    description: "Sky Blue / Bright Yellow",
  },
  {
    id: 4,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [40, 41, 42], 
    color: ["black", "white"], 
    type: "Casual shoes",
    gender: "Women",
    soldOutSizes: [41],
    description: "Classic Black / Pure White",
  },
  {
    id: 5,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "Sale",
    size: [39, 40, 41, 42], 
    color: ["green", "white"], 
    type: "Hiking",
    gender: "Women",
    soldOutSizes: [39],
    description: "Forest Green / Soft White",
  },
  {
    id: 6,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [41, 42, 43], 
    color: ["blue", "green"], 
    type: "Sneaker",
    gender: "Men",
    soldOutSizes: [43],
    description: "Navy Blue / Army Green",
  },
  {
    id: 7,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [38, 39, 40], 
    color: ["blue", "black"], 
    type: "Casual shoes",
    gender: "Women",
    soldOutSizes: [38],
    description: "Deep Blue / Matte Black",
  },
  {
    id: 8,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "Sale",
    size: [43, 44, 45], 
    color: ["green", "orange"], 
    type: "Golf",
    gender: "Men",
    soldOutSizes: [44],
    description: "Lush Green / Sporty Orange",
  },
  {
    id: 9,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [39, 40, 42], 
    color: ["yellow", "blue"], 
    type: "Basketball",
    gender: "Women",
    soldOutSizes: [42],
    description: "Bright Yellow / Electric Blue",
  },
  {
    id: 10,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [38, 39, 40], 
    color: ["white", "gray"], 
    type: "Casual shoes",
    gender: "Women",
    soldOutSizes: [39],
    description: "Pure White / Charcoal Gray",
  },
  {
    id: 11,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "Sale",
    size: [42, 43, 44], 
    color: ["green", "black"], 
    type: "Sneaker",
    gender: "Men",
    soldOutSizes: [42],
    description: "Moss Green / Jet Black",
  },
  {
    id: 12,
    title: "ADIDAS 4DFWD 2 RUNNING SHOES",
    image: S3,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [39, 40, 41], 
    color: ["blue", "green"], 
    type: "Hiking",
    gender: "Women",
    soldOutSizes: [40],
    description: "Sky Blue / Olive Green",
  },
  {
    id: 13,
    title: "ADIDAS ULTRABOOST 1.0 MIAMI",
    image: S1,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "New",
    size: [38, 39, 40], 
    color: ["white", "red"], 
    type: "Casual shoes",
    gender: "Women",
    soldOutSizes: [39],
    description: "Snow White / Bold Red",
  },
  {
    id: 14,
    title: "ADIDAS OZELIA SHOES Green",
    image: S2,
    images: [S11, S12, S13, S14],
    price: 125,
    tag: "Sale",
    size: [40, 41, 42], 
    color: ["green", "yellow"], 
    type: "Casual shoes",
    gender: "Men",
    soldOutSizes: [40],
    description: "Neon Green / Mustard Yellow",
  },
];
